"""
SMPP Protocol Module

This module contains the core SMPP protocol implementation including
PDU definitions, constants, and protocol utilities.
"""

from .codec import (
    calculate_pdu_length,
    decode_cstring,
    decode_integer,
    decode_message_with_encoding,
    encode_cstring,
    encode_integer,
    encode_message_with_encoding,
    pack_tlv_parameter,
    unpack_tlv_parameter,
    validate_field_length,
)
from .constants import (
    CommandId,
    CommandStatus,
    DataCoding,
    EsmClass,
    InterfaceVersion,
    MessageState,
    NpiType,
    OptionalTag,
    PriorityFlag,
    RegisteredDelivery,
    ReplaceIfPresentFlag,
    TonType,
    get_error_message,
    get_request_command_id,
    get_response_command_id,
    is_response_command,
)
from .pdu import (
    PDU,
    PDU_CLASSES,
    AlertNotification,
    BindReceiver,
    BindReceiverResp,
    BindRequestPDU,
    BindResponsePDU,
    BindTransceiver,
    BindTransceiverResp,
    BindTransmitter,
    BindTransmitterResp,
    DataSm,
    DataSmResp,
    DeliverSm,
    DeliverSmResp,
    EmptyBodyPDU,
    EnquireLink,
    EnquireLinkResp,
    GenericNack,
    MessagePDU,
    Outbind,
    QuerySm,
    QuerySmResp,
    RequestPDU,
    ResponsePDU,
    SubmitSm,
    SubmitSmResp,
    TLVParameter,
    Unbind,
    UnbindResp,
    create_bind_pdu,
    create_enquire_link_pdu,
    create_error_response,
    create_generic_nack_pdu,
    create_pdu,
    create_request_pdu,
    create_response_pdu,
    create_submit_sm_pdu,
    decode_pdu,
    get_pdu_class,
    get_pdu_name,
    is_command_supported,
)
from .validation import (
    validate_address,
    validate_bind_parameters,
    validate_command_id,
    validate_data_coding,
    validate_esm_class,
    validate_message_length,
    validate_optional_parameter,
    validate_password,
    validate_pdu_structure,
    validate_priority_flag,
    validate_registered_delivery,
    validate_sequence_number,
    validate_submit_sm_parameters,
    validate_system_id,
)

__all__ = [
    # Constants
    'CommandId',
    'CommandStatus',
    'DataCoding',
    'EsmClass',
    'InterfaceVersion',
    'NpiType',
    'PriorityFlag',
    'RegisteredDelivery',
    'ReplaceIfPresentFlag',
    'TonType',
    'MessageState',
    'OptionalTag',
    'get_error_message',
    'is_response_command',
    'get_response_command_id',
    'get_request_command_id',
    # Base PDU Classes
    'PDU',
    'TLVParameter',
    'RequestPDU',
    'ResponsePDU',
    'BindRequestPDU',
    'BindResponsePDU',
    'MessagePDU',
    'EmptyBodyPDU',
    # Bind PDUs
    'BindReceiver',
    'BindReceiverResp',
    'BindTransceiver',
    'BindTransceiverResp',
    'BindTransmitter',
    'BindTransmitterResp',
    'Unbind',
    'UnbindResp',
    'Outbind',
    # Message PDUs
    'SubmitSm',
    'SubmitSmResp',
    'DeliverSm',
    'DeliverSmResp',
    # Session PDUs
    'EnquireLink',
    'EnquireLinkResp',
    'GenericNack',
    'AlertNotification',
    'DataSm',
    'DataSmResp',
    'QuerySm',
    'QuerySmResp',
    # Factory functions
    'create_pdu',
    'create_request_pdu',
    'create_response_pdu',
    'create_error_response',
    'decode_pdu',
    'get_pdu_class',
    'get_pdu_name',
    'is_command_supported',
    'create_bind_pdu',
    'create_submit_sm_pdu',
    'create_enquire_link_pdu',
    'create_generic_nack_pdu',
    'PDU_CLASSES',
    # Codec utilities
    'encode_cstring',
    'decode_cstring',
    'encode_integer',
    'decode_integer',
    'validate_field_length',
    'encode_message_with_encoding',
    'decode_message_with_encoding',
    'pack_tlv_parameter',
    'unpack_tlv_parameter',
    'calculate_pdu_length',
    # Validation
    'validate_system_id',
    'validate_password',
    'validate_address',
    'validate_message_length',
    'validate_pdu_structure',
    'validate_data_coding',
    'validate_esm_class',
    'validate_priority_flag',
    'validate_registered_delivery',
    'validate_sequence_number',
    'validate_command_id',
    'validate_bind_parameters',
    'validate_submit_sm_parameters',
    'validate_optional_parameter',
]
